@server = https://nilolp-curly-pancake-p46p7wvv7w5c6v7r-8080.preview.app.github.dev

@apiserver = {{server}}/api/curso

###
GET {{server}}
###

GET {{server}}/codigo
###

GET  {{server}}/nombre-completo

###
GET {{apiserver}}/listar
###

POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=Nami&creditos=15
###

DELETE {{apiserver}}/eliminar
Content-Type:  application/x-www-form-urlencoded

id=1